### ISSUE TITLE
Комментарий ревьюера

### ISSUE THREAD

**Issue by Sekai-no-uragawa** [DmitriyTol/Learning-with-Teacher#1]
## Комментарий ревьюера

Привет, Дмитрий! Меня зовут Михаил Костин, я буду проверять этот проект. Спасибо за проделанную работу! Предлагаю общаться на «ты».

*Давай смотреть, что получилось!*

В твоем проекте выполнено большинство необходимых пунктов:
- ✔️Работа над проектом велась последовательно и разбита на отдельные коммиты
- ✔️Описание коммитов соответствуют содержимому
- ✔️Заполнен файл описания проeкта readme.txt 

❌Однако остался один момент, необходимый для принятия проекта — **"Создать issue с возможными улучшениями проекта."**

Дополнительно, но необязательно (если хочешь улучшить этот проект или чтобы учесть при самостоятельном использовании github):
- readme в формате txt тоже можно использовать, но он совершенно не функционален. Лучше использовать формат Markdown. readme .md — markdown файл, у него простой синтаксис разметки, оформлять можно очень красиво и функционально, [Шпаргалка](https://www.markdownguide.org/basic-syntax/)
- Заполняй About репозитория, так будет легче производить навигацию по твоему github.

## Итоговый комментарий ревьюера
Жду твоих правок, общаться предлагаю в этом issue
Надеюсь, комментарии помогут закончить проект. Постараюсь повторно проверить твой проект как можно быстрее.

**Comment by DmitriyTol** [comment]
Привет, рад с тобой поработать!
Добавил issue, что-то совсем из головы вылетело
А касательно дополнительных пунктов:
- Как правильно заполнять About?
- И не особо знаком с Markdown, честно говоря, я так понимаю, это отдельный язык разметки? Как и где удобнее с ним работать?

**Comment by Sekai-no-uragawa** [comment]
Работа зачтена. На счет вопросов:

* About заполнить можно тут в шапке репозитория в шестеренке.
![image](https://user-images.githubusercontent.com/96841762/195438450-348bfa6c-9bf9-4478-be85-69c36b160c01.png)
* Markdown достаточно прост. Можно сразу писать в github, тут есть Preview или же воспользоваться онлайн-редактором типа [такого](https://dillinger.io/)

Твой проект готов :) Надеюсь, тебе понравилось пользоваться системой версионирования — это действительно очень полезный и удобный инструмент.
